- name: Install GoLang
  ansible.builtin.yum:
    name: golang
    state: present

- name: App Pre-requisites
  ansible.builtin.import_tasks:
    file: app_presetup.yml

- name: Install Go Dependencies
  ansible.builtin.shell:
    cmd: |
      cd /app && go mod init {{ component }} && go get && go build

- name: SystemD Setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

