- name: Setup Template
  ansible.builtin.template:
    src: mbranch.xml
    dest: /tmp/mbranch.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/mbranch.xml') }}"
    name: "{{item}}"
    password: admin123
    url: http://172.31.47.188:8080
    user: admin