- name: Create Jenkins Jobs
  hosts: localhost
  connection: local
  vars:
    sp_jobs:
      - roboshop-terraform
      - roboshop-ansible
      - roboshop-kubernetes
    mp_jobs:
      - cart
      - catalogue
      - user
      - shipping
      - payment
      - frontend
      - aws-parameter-init-container
      - schema-load-init-container
  roles:
    - jenkins-jobs